import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import json
import os
from sklearn.metrics import roc_curve, precision_recall_curve

st.set_page_config(page_title="Model Performance", layout="wide")
st.title("🧠 Goldilocks Model Performance")

# =====================================================
# LOAD PRE-CALCULATED METRICS & DATA
# =====================================================
@st.cache_data
def load_performance_data():
    # Load the JSON metrics generated by your training script
    metrics_path = os.path.join("metrics", "metrics.json")
    if not os.path.exists(metrics_path):
        st.error("metrics.json not found. Please run your training script first.")
        st.stop()
        
    with open(metrics_path, "r") as f:
        return json.load(f)

metrics = load_performance_data()

# =====================================================
# DISPLAY EVALUATION METRICS
# =====================================================
st.markdown("### Key Evaluation Metrics")
col1, col2, col3, col4, col5 = st.columns(5)

# Extract values from metrics.json
col1.metric("ROC-AUC", f"{metrics['roc_auc']:.3f}")
col2.metric("PR-AUC", f"{metrics['pr_auc']:.3f}")
col3.metric("Precision", f"{metrics['precision']:.3f}")
col4.metric("Recall", f"{metrics['recall']:.3f}")
col5.metric("F1 Score", f"{metrics['f1_score']:.3f}")

st.info(f"Optimization: Using Best F1 Threshold of **{metrics['best_threshold']:.4f}**")
st.markdown("---")

# =====================================================
# VISUALIZATIONS
# =====================================================
row1_col1, row1_col2 = st.columns(2)

with row1_col1:
    # 1. CONFUSION MATRIX HEATMAP
    st.subheader("Confusion Matrix")
    # Convert list from JSON back to numpy array
    cm = np.array(metrics['confusion_matrix'])
    
    fig_cm = px.imshow(
        cm,
        text_auto=True,
        labels=dict(x="Predicted", y="Actual"),
        x=["Non-Fraud", "Fraud"],
        y=["Non-Fraud", "Fraud"],
        color_continuous_scale="Blues",
        aspect="auto"
    )
    st.plotly_chart(fig_cm, use_container_width=True)

with row1_col2:
    # 2. ROC CURVE
    # To draw the actual curve, we need the raw predictions (probabilities)
    # If probabilities aren't in JSON, we display the AUC score in a placeholder
    st.subheader("Performance Summary")
    
    # Example of a Gauage Chart for ROC-AUC
    fig_gauge = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = metrics['roc_auc'],
        title = {'text': "ROC-AUC Score"},
        gauge = {'axis': {'range': [0, 1]},
                 'bar': {'color': "#1f77b4"},
                 'steps' : [
                     {'range': [0, 0.7], 'color': "lightgray"},
                     {'range': [0.7, 0.9], 'color': "gray"}]}))
    
    fig_gauge.update_layout(height=350)
    st.plotly_chart(fig_gauge, use_container_width=True)

# -----------------------------------------------------
# Note on Curves:
# Since metrics.json only stores single values, 
# full ROC/PR curves require re-running predict_proba on X_test.
# -----------------------------------------------------
st.success("Visualizations loaded from generated training metrics.")